import org.junit.Assert;

public class Test {

    @org.junit.Test
    public void equalTest() {

        Assert.assertEquals("YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO", "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO\n" +
                "YES\n" +
                "NO\n" +
                "NO\n" +
                "NO\n" +
                "YES\n" +
                "YES\n" +
                "NO");
    }
}
